# Generated by Django 4.2.30 on 2026-06-19 08:48

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CourseCompletionSummary",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("user_id", models.PositiveIntegerField(db_index=True)),
                ("course_id", models.CharField(db_index=True, max_length=255)),
                ("complete_count", models.PositiveIntegerField(default=0)),
                ("incomplete_count", models.PositiveIntegerField(default=0)),
                ("locked_count", models.PositiveIntegerField(default=0)),
                (
                    "percent_complete",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=6, null=True
                    ),
                ),
                ("computed_at", models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name="CourseCompletionSummaryDirty",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("user_id", models.PositiveIntegerField(db_index=True)),
                ("course_id", models.CharField(db_index=True, max_length=255)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["course_id", "user_id"], name="op_dirty_course_user_idx"
                    ),
                    models.Index(fields=["modified"], name="op_dirty_modified_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="coursecompletionsummarydirty",
            constraint=models.UniqueConstraint(
                fields=("course_id", "user_id"), name="op_unique_dirty_course_user"
            ),
        ),
        migrations.AddIndex(
            model_name="coursecompletionsummary",
            index=models.Index(
                fields=["course_id", "user_id"], name="op_course_user_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coursecompletionsummary",
            index=models.Index(
                fields=["course_id", "computed_at"], name="op_course_computed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coursecompletionsummary",
            index=models.Index(
                fields=["user_id", "computed_at"], name="op_user_computed_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="coursecompletionsummary",
            constraint=models.UniqueConstraint(
                fields=("course_id", "user_id"), name="op_unique_course_user_summary"
            ),
        ),
    ]
